### ISSUE TITLE
Please use a privacy-respecting default search engine.

### ISSUE THREAD

**Issue by nipos** [censorship-no/ceno-browser-archive#9]
I just tried Ceno and was shocked to see that it actually uses Google as default search engine, which is the worst possible option for privacy reasons.
It's a shame that upstream Firefox has to make this choice because they depend on Googles money, but as Ceno likely doesn't receive any money from Google, could you please set any more privacy-respecting alternative as default?
I'm personally quite happy with https://metager.de but probably it's too focused on the German-speaking countries.
Other popular and (more or less) trustworthy solutions are https://swisscows.com , https://search.brave.com or https://duckduckgo.com

**Comment by paidforby** [comment]
Hey @nipos this has been fixed in the latest releases of Ceno, see the [release notes](https://github.com/censorship-no/ceno-browser/releases) and try it out for yourself from one of our download options, https://censorship.no/download, or maybe from F-droid, https://f-droid.org/en/packages/ie.equalit.ceno/ :slightly_smiling_face:
